Silence some pyflakes warnings
bootlin/elixir pull request #191
Opened 2020-10-20 19:42 UTC by xrmx

2020-10-21 05:17 UTC, MaximeChretien requested changes
Hi !
I think the whole line can be deleted here since the function just return a value and we don't use that value.

Edit : On that commit : https://github.com/bootlin/elixir/pull/191/commits/99ac2ee8063fb3f680fcb7cc5568cc98fed6a5ae
I didn't used the right comment section :/

2020-10-21 06:49 UTC, xrmx commented
Updated!

2020-10-24 08:36 UTC, MaximeChretien approved these changes

2020-10-26 15:25 UTC, michaelopdenacker commented
Many thanks @MaximeChretien for the review.
Thanks for these improvements!

2020-10-26 15:25 UTC, merged