update.py: Filter defs when indexing refs
bootlin/elixir pull request #204
Opened 2020-12-07 11:11 UTC by MaximeChretien

This resolves issue https://github.com/bootlin/elixir/issues/196

To do that we store each identifier definition in a dictionary where each key is equal to identifier*1 000 000 + line number.

This doesn't seems to slow down update.py so indexing time should remain the same.
However there can be a problem if a file has more than 1 000 000 lines but I think such file doesn't exists so it should be fine.
If this problem occurs, we'll have to multiply the identifier value with an higher power of 10 in the dictionary keys.

2020-12-07 13:10 UTC, cxw42 requested changes

2020-12-07 13:10 UTC, cxw42 commented on update.py
> +                    defs_idxes[idx*1000000+line] = ident
I think the 1000000 should be a named constant (no magic numbers! :) ).  As you pointed out in the PR, we will have to change this number if a source file ever reaches 1M lines.  It would be good to have to change it in only one place.

2020-12-07 13:13 UTC, MaximeChretien commented on update.py
> +                    defs_idxes[idx*1000000+line] = ident
Oh that's totally right ! I'll change that right now

2020-12-08 13:49 UTC, cxw42 approved these changes

2020-12-10 08:40 UTC, michaelopdenacker commented
Hi Maxime
Many thanks for this nice feature.
I'm happy to merge it now and start building a new database right now.
Thanks again
Michael

2020-12-10 08:40 UTC, merged

2020-12-21 09:22 UTC, michaelopdenacker commented
Hi Maxime
The new database is up on the production server.
Thanks again :)
Michael.