Indexing scripts rework
bootlin/elixir pull request #348
Opened 2024-11-08 14:40 UTC by tleb

Hi!

```
⟩ git diff --stat=80 master..indexing-scripts-rework
 README.adoc                  |  35 ++--------
 docker/Dockerfile            |   4 +-
 utils/common.sh              |  24 -------
 utils/index                  | 157 +++++++++++++++++++++++++++++++++++++++++++
 utils/index-all-repositories |  96 --------------------------
 utils/index-repository       |  29 --------
 utils/pack-repositories      |  48 -------------
 utils/update-elixir-data     |  38 -----------
 8 files changed, 165 insertions(+), 266 deletions(-)
```

This is a big rework of the wrapper scripts around indexing. Notice how we remove all scripts to replace by a single one called `utils/index`.

 - It takes as first argument the data path, to avoid using hardcoded paths. (It also avoids hardcoded `update.py` path.)
 - It started from `index/index-repository`, so it can be called in the same manner (eg `./utils/index /srv/elixir-data musl https://git.musl-libc.org/git/musl`). This will init the project (if not already existing), add remote (if not already existing), fetch and index.
 - It gained the ability to be called like this: `./utils/index /srv/elixir-data musl`. It will notice that we want `musl` and automatically add the right remote URL from its list. This is matched on the project name.
 - It can do `./utils/index /srv/elixir-data --all`. This will add all known projects remote (if not already existing) and fetch+index them. Replaces `index-all-repositories` and `update-elixir-data`.
 - It does something similar to `pack-repositories`, but automatically. Previous setup meant manual intervention was required. We remove the section about `pack-repositories` from the README.

Opinions @fstachura? Commit messages contain much more information.

Closes #342

2025-01-28 12:51 UTC, fstachura requested changes

2025-01-28 12:51 UTC, fstachura commented on bench.py
> +config = Config(project_dir='/home/tleb/prog/public/elixir-data',
Is this script meant to be in the PR?

2025-01-28 12:51 UTC, fstachura commented on bench.py
> +config = Config(project_dir='/home/tleb/prog/public/elixir-data',
I think I would leave the whole "WIP benchmark scripts" to another PR. Same with "WIP: limit Linux tags"

2025-01-28 12:51 UTC, fstachura commented on elixir/web.py
> +    html_code_block = sub(r'href="#codeline-(\d+)', 'name="L\\1" id="L\\1" href="#L\\1', html_code_block)
Again, this a part of the "WIP benchmark scripts" commit, but I planned to do it for a long time. I'm just not 100% sure if everything will work exactly the same after converting all regexes to raw strings. It probably should though

2025-01-28 12:51 UTC, fstachura commented on utils/index
> +add_default_remotes $1 $# $2 llvm https://github.com/llvm/llvm-project.git
I think it would be better to separate the list of known remotes to another file. Keeps data/config and code separate.

2025-01-28 12:51 UTC, fstachura commented on utils/index
> +    git -C $1/repo -c init.defaultBranch=main init --bare
Are you sure setting the default branch to main is a good idea? Many projects use master (for example Linux). Technically, Elixir works on tags

2025-01-28 12:51 UTC, fstachura commented on utils/index
> +        $git gc --auto
I'm still not convinced that `git gc` does what we want. I think we want to optimize for fast blob access, not necessarily storage?

2025-01-28 13:04 UTC, tleb commented on bench.py
> +config = Config(project_dir='/home/tleb/prog/public/elixir-data',
Of course, it is only there because I am benchmarking on various machines and pushed a branch. I should have used another branch. Those two commits are indeed to be ignored.

2025-01-28 13:06 UTC, tleb commented on utils/index
> +add_default_remotes $1 $# $2 llvm https://github.com/llvm/llvm-project.git
Why? Supporting a new project does require some project-specific code in `projects/*.sh`, so the supported projects are not some config.

2025-01-28 13:07 UTC, tleb commented on utils/index
> +    git -C $1/repo -c init.defaultBranch=main init --bare
From memory, this only avoids a warning on stderr (something like "before the default was master, now it is main, please pick one using the init.defaultBranch configuration option"). As you noted, we do not care about branches!

2025-01-28 13:09 UTC, tleb commented on utils/index
> +        $git gc --auto
`git gc` has been shown to (1) reduce storage requirements and (2) reduce time for some operations.

For an unrelated project, on a kernel repo, I saw a jump from 10s to 600ms for running the command `git describe --match=v6.10`. I am not saying I saw such benefit in the context of Elixir, but I don't think it costs us much to run it from time to time.

2025-01-28 13:09 UTC, tleb commented on elixir/web.py
> +    html_code_block = sub(r'href="#codeline-(\d+)', 'name="L\\1" id="L\\1" href="#L\\1', html_code_block)
I see what you mean, maybe there exists some automated tools that can give us the matching raw string for a given standard string?

2025-01-30 13:20 UTC, fstachura commented on elixir/web.py
> +    html_code_block = sub(r'href="#codeline-(\d+)', 'name="L\\1" id="L\\1" href="#L\\1', html_code_block)
I couldn't find anything automatic. I guess we will just to be careful, I think mostly around backslashes. For now Python just warns, so let's leave it.

2025-01-30 13:37 UTC, fstachura commented on utils/index
> +        $git gc --auto
> For an unrelated project, on a kernel repo, I saw a jump from 10s to 600ms for running the command git describe --match=v6.10

That's not really a benchmark, so I'm still unconvinced. Especially since there are weird performance issues on the new server, and git gc has many config options https://git-scm.com/docs/git-gc#_configuration
I guess the default should be better than nothing, but I think we should be careful

https://git-scm.com/docs/git-repack
> --window=<n>
> --depth=<n>
> 
>    These two options affect how the objects contained in the pack are stored using delta compression. The objects are first internally sorted by type, size and optionally names and compared against the other objects within --window to see if using delta compression saves space. --depth limits the maximum delta depth; making it too deep **affects the performance on the unpacker** side, because delta data needs to be applied that many times to get to the necessary object.
> 
> The default value for --window is 10 and --depth is 50. The maximum depth is 4095.

2025-01-30 14:00 UTC, tleb commented on utils/index
> +        $git gc --auto
That looks mostly like a warning against setting to the extreme. We don't do that and trust `git gc` to have defaults. Either way it is going to be better to run it once in a while than not running it, and I think we agree on that.

2025-01-31 18:37 UTC, closed without merging

2025-01-31 18:48 UTC, tleb commented
Applied on master!

2025-01-31 18:48 UTC, tleb commented on utils/index
> +add_default_remotes $1 $# $2 llvm https://github.com/llvm/llvm-project.git
I agree. Once we have project-specific Python code then we'll have a place to put those URLs.

2025-01-31 18:50 UTC, tleb commented on elixir/web.py
> +    html_code_block = sub(r'href="#codeline-(\d+)', 'name="L\\1" id="L\\1" href="#L\\1', html_code_block)
I didn't apply this patch to avoid dumb mistakes. If we want to do such refactoring we need to really look into it.

2025-01-31 18:50 UTC, tleb commented on bench.py
> +config = Config(project_dir='/home/tleb/prog/public/elixir-data',
Didn't apply those, it was personal scripts. It could deserve to be upstreamed though!